export const PORTFOLIO_REQUEST = "PORTFOLIO_REQUEST";
export const PORTFOLIO_FAILED = "PORTFOLIO_FAILED";
export const PORTFOLIO_SUCCESS = "PORTFOLIO_SUCCESS";
export const PORTFOLIO_DELETE = "PORTFOLIO_DELETE";
export const PORTFOLIO_EDIT = "PORTFOLIO_EDIT";
export const PORTFOLIO_ADDED = "PORTFOLIO_ADDED";
export const SINGLE_PORTFOLIO = "SINGLE_PORTFOLIO";
